/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenFactory,
  ITokenFactoryInterface,
} from "../../../../contracts/launchpad/HoneycombBondingCurveMarket.sol/ITokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isHoneycombToken",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenFactoryInterface {
    return new Interface(_abi) as ITokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenFactory {
    return new Contract(address, _abi, runner) as unknown as ITokenFactory;
  }
}
