/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBondingCurveMarket,
  IBondingCurveMarketInterface,
} from "../../../../contracts/launchpad/HoneycombTokenFactory.sol/IBondingCurveMarket";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "initializeMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBondingCurveMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IBondingCurveMarketInterface {
    return new Interface(_abi) as IBondingCurveMarketInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBondingCurveMarket {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBondingCurveMarket;
  }
}
