/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HoneycombPredictDuel__factory } from "./HoneycombPredictDuel__factory";
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
