/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace HoneycombBountyEscrow {
  export type BountyStruct = {
    id: BigNumberish;
    creatorAgentId: BigNumberish;
    creatorAddress: AddressLike;
    bountyCID: string;
    rewardAmount: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    winningSolutionId: BigNumberish;
    createdAt: BigNumberish;
  };

  export type BountyStructOutput = [
    id: bigint,
    creatorAgentId: bigint,
    creatorAddress: string,
    bountyCID: string,
    rewardAmount: bigint,
    deadline: bigint,
    status: bigint,
    winningSolutionId: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    creatorAgentId: bigint;
    creatorAddress: string;
    bountyCID: string;
    rewardAmount: bigint;
    deadline: bigint;
    status: bigint;
    winningSolutionId: bigint;
    createdAt: bigint;
  };

  export type SolutionStruct = {
    id: BigNumberish;
    bountyId: BigNumberish;
    agentId: BigNumberish;
    solverAddress: AddressLike;
    solutionCID: string;
    createdAt: BigNumberish;
  };

  export type SolutionStructOutput = [
    id: bigint,
    bountyId: bigint,
    agentId: bigint,
    solverAddress: string,
    solutionCID: string,
    createdAt: bigint
  ] & {
    id: bigint;
    bountyId: bigint;
    agentId: bigint;
    solverAddress: string;
    solutionCID: string;
    createdAt: bigint;
  };
}

export interface HoneycombBountyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_DEADLINE_DURATION"
      | "MAX_REWARD"
      | "MIN_DEADLINE_DURATION"
      | "MIN_REWARD"
      | "agentRegistry"
      | "awardSolution"
      | "bounties"
      | "bountyExists"
      | "cancelBounty"
      | "createBounty"
      | "getBounty"
      | "getRoleAdmin"
      | "getSolution"
      | "grantRole"
      | "hasRole"
      | "renounceRole"
      | "revokeRole"
      | "setAgentRegistry"
      | "solutionCounts"
      | "solutions"
      | "submitSolution"
      | "supportsInterface"
      | "totalBounties"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyAwarded"
      | "BountyCancelled"
      | "BountyCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SolutionSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEADLINE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEADLINE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardSolution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSolution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "solutionCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solutions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSolution",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBounties",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEADLINE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_REWARD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEADLINE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_REWARD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountyExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solutionCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solutions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBounties",
    data: BytesLike
  ): Result;
}

export namespace BountyAwardedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    solutionId: BigNumberish,
    solverAddress: AddressLike,
    rewardAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    solutionId: bigint,
    solverAddress: string,
    rewardAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    solutionId: bigint;
    solverAddress: string;
    rewardAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    refundAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    refundAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creatorAgentId: BigNumberish,
    creator: AddressLike,
    bountyCID: string,
    rewardAmount: BigNumberish,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creatorAgentId: bigint,
    creator: string,
    bountyCID: string,
    rewardAmount: bigint,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    creatorAgentId: bigint;
    creator: string;
    bountyCID: string;
    rewardAmount: bigint;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolutionSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    solutionId: BigNumberish,
    agentId: BigNumberish,
    solver: AddressLike,
    solutionCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    solutionId: bigint,
    agentId: bigint,
    solver: string,
    solutionCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    solutionId: bigint;
    agentId: bigint;
    solver: string;
    solutionCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneycombBountyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): HoneycombBountyEscrow;
  waitForDeployment(): Promise<this>;

  interface: HoneycombBountyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_DEADLINE_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_REWARD: TypedContractMethod<[], [bigint], "view">;

  MIN_DEADLINE_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_REWARD: TypedContractMethod<[], [bigint], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  awardSolution: TypedContractMethod<
    [bountyId: BigNumberish, solutionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creatorAgentId: bigint;
        creatorAddress: string;
        bountyCID: string;
        rewardAmount: bigint;
        deadline: bigint;
        status: bigint;
        winningSolutionId: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  bountyExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<
    [agentId: BigNumberish, bountyCID: string, deadlineTimestamp: BigNumberish],
    [bigint],
    "payable"
  >;

  getBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [HoneycombBountyEscrow.BountyStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSolution: TypedContractMethod<
    [bountyId: BigNumberish, solutionId: BigNumberish],
    [HoneycombBountyEscrow.SolutionStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentRegistry: TypedContractMethod<
    [_agentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  solutionCounts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  solutions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        id: bigint;
        bountyId: bigint;
        agentId: bigint;
        solverAddress: string;
        solutionCID: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  submitSolution: TypedContractMethod<
    [bountyId: BigNumberish, agentId: BigNumberish, solutionCID: string],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalBounties: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_DEADLINE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEADLINE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "awardSolution"
  ): TypedContractMethod<
    [bountyId: BigNumberish, solutionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        creatorAgentId: bigint;
        creatorAddress: string;
        bountyCID: string;
        rewardAmount: bigint;
        deadline: bigint;
        status: bigint;
        winningSolutionId: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountyExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [agentId: BigNumberish, bountyCID: string, deadlineTimestamp: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BigNumberish],
    [HoneycombBountyEscrow.BountyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSolution"
  ): TypedContractMethod<
    [bountyId: BigNumberish, solutionId: BigNumberish],
    [HoneycombBountyEscrow.SolutionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[_agentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "solutionCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "solutions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        id: bigint;
        bountyId: bigint;
        agentId: bigint;
        solverAddress: string;
        solutionCID: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitSolution"
  ): TypedContractMethod<
    [bountyId: BigNumberish, agentId: BigNumberish, solutionCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalBounties"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BountyAwarded"
  ): TypedContractEvent<
    BountyAwardedEvent.InputTuple,
    BountyAwardedEvent.OutputTuple,
    BountyAwardedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SolutionSubmitted"
  ): TypedContractEvent<
    SolutionSubmittedEvent.InputTuple,
    SolutionSubmittedEvent.OutputTuple,
    SolutionSubmittedEvent.OutputObject
  >;

  filters: {
    "BountyAwarded(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      BountyAwardedEvent.InputTuple,
      BountyAwardedEvent.OutputTuple,
      BountyAwardedEvent.OutputObject
    >;
    BountyAwarded: TypedContractEvent<
      BountyAwardedEvent.InputTuple,
      BountyAwardedEvent.OutputTuple,
      BountyAwardedEvent.OutputObject
    >;

    "BountyCancelled(uint256,address,uint256,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SolutionSubmitted(uint256,uint256,uint256,address,string,uint256)": TypedContractEvent<
      SolutionSubmittedEvent.InputTuple,
      SolutionSubmittedEvent.OutputTuple,
      SolutionSubmittedEvent.OutputObject
    >;
    SolutionSubmitted: TypedContractEvent<
      SolutionSubmittedEvent.InputTuple,
      SolutionSubmittedEvent.OutputTuple,
      SolutionSubmittedEvent.OutputObject
    >;
  };
}
