/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HoneycombAIAgentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "agentBalances"
      | "calculatePayment"
      | "feeVault"
      | "getAgentBalance"
      | "getPlatformFeeBps"
      | "isPaymentUsed"
      | "owner"
      | "payForUsage"
      | "registry"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateFeeVault"
      | "usedPaymentHashes"
      | "withdrawAgentEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EarningsWithdrawn"
      | "FeeVaultUpdated"
      | "OwnershipTransferred"
      | "UsagePaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentBalances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePayment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAgentBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payForUsage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedPaymentHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAgentEarnings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedPaymentHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAgentEarnings",
    data: BytesLike
  ): Result;
}

export namespace EarningsWithdrawnEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    to: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeVaultUpdatedEvent {
  export type InputTuple = [
    oldVault: AddressLike,
    newVault: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldVault: string,
    newVault: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsagePaidEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    user: AddressLike,
    units: BigNumberish,
    totalAmount: BigNumberish,
    agentAmount: BigNumberish,
    platformFee: BigNumberish,
    paymentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    user: string,
    units: bigint,
    totalAmount: bigint,
    agentAmount: bigint,
    platformFee: bigint,
    paymentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    user: string;
    units: bigint;
    totalAmount: bigint;
    agentAmount: bigint;
    platformFee: bigint;
    paymentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneycombAIAgentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): HoneycombAIAgentEscrow;
  waitForDeployment(): Promise<this>;

  interface: HoneycombAIAgentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  agentBalances: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  calculatePayment: TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalCost: bigint;
        platformFee: bigint;
        agentEarnings: bigint;
      }
    ],
    "view"
  >;

  feeVault: TypedContractMethod<[], [string], "view">;

  getAgentBalance: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  getPlatformFeeBps: TypedContractMethod<[], [bigint], "view">;

  isPaymentUsed: TypedContractMethod<
    [paymentHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payForUsage: TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [string],
    "payable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFeeVault: TypedContractMethod<
    [newFeeVault: AddressLike],
    [void],
    "nonpayable"
  >;

  usedPaymentHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  withdrawAgentEarnings: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentBalances"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePayment"
  ): TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalCost: bigint;
        platformFee: bigint;
        agentEarnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentBalance"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPaymentUsed"
  ): TypedContractMethod<[paymentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payForUsage"
  ): TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeVault"
  ): TypedContractMethod<[newFeeVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedPaymentHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawAgentEarnings"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EarningsWithdrawn"
  ): TypedContractEvent<
    EarningsWithdrawnEvent.InputTuple,
    EarningsWithdrawnEvent.OutputTuple,
    EarningsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FeeVaultUpdated"
  ): TypedContractEvent<
    FeeVaultUpdatedEvent.InputTuple,
    FeeVaultUpdatedEvent.OutputTuple,
    FeeVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UsagePaid"
  ): TypedContractEvent<
    UsagePaidEvent.InputTuple,
    UsagePaidEvent.OutputTuple,
    UsagePaidEvent.OutputObject
  >;

  filters: {
    "EarningsWithdrawn(uint256,address,uint256,uint256)": TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;
    EarningsWithdrawn: TypedContractEvent<
      EarningsWithdrawnEvent.InputTuple,
      EarningsWithdrawnEvent.OutputTuple,
      EarningsWithdrawnEvent.OutputObject
    >;

    "FeeVaultUpdated(address,address,uint256)": TypedContractEvent<
      FeeVaultUpdatedEvent.InputTuple,
      FeeVaultUpdatedEvent.OutputTuple,
      FeeVaultUpdatedEvent.OutputObject
    >;
    FeeVaultUpdated: TypedContractEvent<
      FeeVaultUpdatedEvent.InputTuple,
      FeeVaultUpdatedEvent.OutputTuple,
      FeeVaultUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UsagePaid(uint256,address,uint256,uint256,uint256,uint256,bytes32,uint256)": TypedContractEvent<
      UsagePaidEvent.InputTuple,
      UsagePaidEvent.OutputTuple,
      UsagePaidEvent.OutputObject
    >;
    UsagePaid: TypedContractEvent<
      UsagePaidEvent.InputTuple,
      UsagePaidEvent.OutputTuple,
      UsagePaidEvent.OutputObject
    >;
  };
}
