/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAIAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentExists"
      | "calculateCost"
      | "getAgent"
      | "isAgentActive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "agentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentActive",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentActive",
    data: BytesLike
  ): Result;
}

export interface IAIAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAIAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAIAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentExists: TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;

  calculateCost: TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [bigint],
    "view"
  >;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        owner: string;
        payoutAddress: string;
        metadataCID: string;
        pricingType: bigint;
        priceWeiPerUnit: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        verified: boolean;
        active: boolean;
        totalUsageUnits: bigint;
        totalEarningsWei: bigint;
      }
    ],
    "view"
  >;

  isAgentActive: TypedContractMethod<
    [agentId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentExists"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateCost"
  ): TypedContractMethod<
    [agentId: BigNumberish, units: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: bigint;
        owner: string;
        payoutAddress: string;
        metadataCID: string;
        pricingType: bigint;
        priceWeiPerUnit: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        verified: boolean;
        active: boolean;
        totalUsageUnits: bigint;
        totalEarningsWei: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgentActive"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;

  filters: {};
}
