/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace HoneycombPredictDuel {
  export type DuelStruct = {
    id: BigNumberish;
    assetId: string;
    creatorAgentId: BigNumberish;
    creatorAddress: AddressLike;
    creatorDirection: BigNumberish;
    stakeAmount: BigNumberish;
    durationSeconds: BigNumberish;
    joinerAgentId: BigNumberish;
    joinerAddress: AddressLike;
    startPrice: BigNumberish;
    endPrice: BigNumberish;
    startTs: BigNumberish;
    endTs: BigNumberish;
    status: BigNumberish;
    winner: AddressLike;
    payout: BigNumberish;
    fee: BigNumberish;
    createdAt: BigNumberish;
  };

  export type DuelStructOutput = [
    id: bigint,
    assetId: string,
    creatorAgentId: bigint,
    creatorAddress: string,
    creatorDirection: bigint,
    stakeAmount: bigint,
    durationSeconds: bigint,
    joinerAgentId: bigint,
    joinerAddress: string,
    startPrice: bigint,
    endPrice: bigint,
    startTs: bigint,
    endTs: bigint,
    status: bigint,
    winner: string,
    payout: bigint,
    fee: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    assetId: string;
    creatorAgentId: bigint;
    creatorAddress: string;
    creatorDirection: bigint;
    stakeAmount: bigint;
    durationSeconds: bigint;
    joinerAgentId: bigint;
    joinerAddress: string;
    startPrice: bigint;
    endPrice: bigint;
    startTs: bigint;
    endTs: bigint;
    status: bigint;
    winner: string;
    payout: bigint;
    fee: bigint;
    createdAt: bigint;
  };
}

export interface HoneycombPredictDuelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_DURATION"
      | "MAX_STAKE"
      | "MIN_DURATION"
      | "MIN_STAKE"
      | "ORACLE_ROLE"
      | "agentRegistry"
      | "cancelDuel"
      | "createDuel"
      | "duelExists"
      | "duels"
      | "expireDuel"
      | "feePercentage"
      | "feeTreasury"
      | "getDuel"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "joinDuel"
      | "renounceRole"
      | "revokeRole"
      | "setAgentRegistry"
      | "setFeePercentage"
      | "setFeeTreasury"
      | "settleDuel"
      | "supportsInterface"
      | "totalDuels"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DuelCancelled"
      | "DuelCreated"
      | "DuelExpired"
      | "DuelJoined"
      | "DuelSettled"
      | "FeeTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDuel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDuel",
    values: [BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duelExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "duels", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "expireDuel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDuel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinDuel",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleDuel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDuels",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelDuel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createDuel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duelExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expireDuel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDuel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinDuel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleDuel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDuels", data: BytesLike): Result;
}

export namespace DuelCancelledEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    creator: string,
    refundAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    creator: string;
    refundAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCreatedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    creatorAgentId: BigNumberish,
    creator: AddressLike,
    assetId: string,
    direction: BigNumberish,
    stakeAmount: BigNumberish,
    durationSeconds: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    creatorAgentId: bigint,
    creator: string,
    assetId: string,
    direction: bigint,
    stakeAmount: bigint,
    durationSeconds: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    creatorAgentId: bigint;
    creator: string;
    assetId: string;
    direction: bigint;
    stakeAmount: bigint;
    durationSeconds: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelExpiredEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    refundAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    refundAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    refundAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelJoinedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    joinerAgentId: BigNumberish,
    joiner: AddressLike,
    startPrice: BigNumberish,
    startTs: BigNumberish,
    endTs: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    joinerAgentId: bigint,
    joiner: string,
    startPrice: bigint,
    startTs: bigint,
    endTs: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    joinerAgentId: bigint;
    joiner: string;
    startPrice: bigint;
    startTs: bigint;
    endTs: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelSettledEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    winner: AddressLike,
    endPrice: BigNumberish,
    payout: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    winner: string,
    endPrice: bigint,
    payout: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    winner: string;
    endPrice: bigint;
    payout: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeTransferredEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    treasury: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    treasury: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    treasury: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneycombPredictDuel extends BaseContract {
  connect(runner?: ContractRunner | null): HoneycombPredictDuel;
  waitForDeployment(): Promise<this>;

  interface: HoneycombPredictDuelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_STAKE: TypedContractMethod<[], [bigint], "view">;

  MIN_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  cancelDuel: TypedContractMethod<[duelId: BigNumberish], [void], "nonpayable">;

  createDuel: TypedContractMethod<
    [
      agentId: BigNumberish,
      assetId: string,
      direction: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  duelExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  duels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        assetId: string;
        creatorAgentId: bigint;
        creatorAddress: string;
        creatorDirection: bigint;
        stakeAmount: bigint;
        durationSeconds: bigint;
        joinerAgentId: bigint;
        joinerAddress: string;
        startPrice: bigint;
        endPrice: bigint;
        startTs: bigint;
        endTs: bigint;
        status: bigint;
        winner: string;
        payout: bigint;
        fee: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  expireDuel: TypedContractMethod<[duelId: BigNumberish], [void], "nonpayable">;

  feePercentage: TypedContractMethod<[], [bigint], "view">;

  feeTreasury: TypedContractMethod<[], [string], "view">;

  getDuel: TypedContractMethod<
    [duelId: BigNumberish],
    [HoneycombPredictDuel.DuelStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  joinDuel: TypedContractMethod<
    [duelId: BigNumberish, agentId: BigNumberish, startPrice: BigNumberish],
    [void],
    "payable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentRegistry: TypedContractMethod<
    [_agentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeePercentage: TypedContractMethod<
    [_feePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeTreasury: TypedContractMethod<
    [_feeTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  settleDuel: TypedContractMethod<
    [duelId: BigNumberish, endPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalDuels: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelDuel"
  ): TypedContractMethod<[duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDuel"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      assetId: string,
      direction: BigNumberish,
      durationSeconds: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "duelExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "duels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        assetId: string;
        creatorAgentId: bigint;
        creatorAddress: string;
        creatorDirection: bigint;
        stakeAmount: bigint;
        durationSeconds: bigint;
        joinerAgentId: bigint;
        joinerAddress: string;
        startPrice: bigint;
        endPrice: bigint;
        startTs: bigint;
        endTs: bigint;
        status: bigint;
        winner: string;
        payout: bigint;
        fee: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "expireDuel"
  ): TypedContractMethod<[duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDuel"
  ): TypedContractMethod<
    [duelId: BigNumberish],
    [HoneycombPredictDuel.DuelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinDuel"
  ): TypedContractMethod<
    [duelId: BigNumberish, agentId: BigNumberish, startPrice: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[_agentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeePercentage"
  ): TypedContractMethod<[_feePercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeTreasury"
  ): TypedContractMethod<[_feeTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleDuel"
  ): TypedContractMethod<
    [duelId: BigNumberish, endPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalDuels"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DuelCancelled"
  ): TypedContractEvent<
    DuelCancelledEvent.InputTuple,
    DuelCancelledEvent.OutputTuple,
    DuelCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DuelCreated"
  ): TypedContractEvent<
    DuelCreatedEvent.InputTuple,
    DuelCreatedEvent.OutputTuple,
    DuelCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DuelExpired"
  ): TypedContractEvent<
    DuelExpiredEvent.InputTuple,
    DuelExpiredEvent.OutputTuple,
    DuelExpiredEvent.OutputObject
  >;
  getEvent(
    key: "DuelJoined"
  ): TypedContractEvent<
    DuelJoinedEvent.InputTuple,
    DuelJoinedEvent.OutputTuple,
    DuelJoinedEvent.OutputObject
  >;
  getEvent(
    key: "DuelSettled"
  ): TypedContractEvent<
    DuelSettledEvent.InputTuple,
    DuelSettledEvent.OutputTuple,
    DuelSettledEvent.OutputObject
  >;
  getEvent(
    key: "FeeTransferred"
  ): TypedContractEvent<
    FeeTransferredEvent.InputTuple,
    FeeTransferredEvent.OutputTuple,
    FeeTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DuelCancelled(uint256,address,uint256,uint256)": TypedContractEvent<
      DuelCancelledEvent.InputTuple,
      DuelCancelledEvent.OutputTuple,
      DuelCancelledEvent.OutputObject
    >;
    DuelCancelled: TypedContractEvent<
      DuelCancelledEvent.InputTuple,
      DuelCancelledEvent.OutputTuple,
      DuelCancelledEvent.OutputObject
    >;

    "DuelCreated(uint256,uint256,address,string,uint8,uint256,uint256,uint256)": TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;
    DuelCreated: TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;

    "DuelExpired(uint256,uint256,uint256)": TypedContractEvent<
      DuelExpiredEvent.InputTuple,
      DuelExpiredEvent.OutputTuple,
      DuelExpiredEvent.OutputObject
    >;
    DuelExpired: TypedContractEvent<
      DuelExpiredEvent.InputTuple,
      DuelExpiredEvent.OutputTuple,
      DuelExpiredEvent.OutputObject
    >;

    "DuelJoined(uint256,uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DuelJoinedEvent.InputTuple,
      DuelJoinedEvent.OutputTuple,
      DuelJoinedEvent.OutputObject
    >;
    DuelJoined: TypedContractEvent<
      DuelJoinedEvent.InputTuple,
      DuelJoinedEvent.OutputTuple,
      DuelJoinedEvent.OutputObject
    >;

    "DuelSettled(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DuelSettledEvent.InputTuple,
      DuelSettledEvent.OutputTuple,
      DuelSettledEvent.OutputObject
    >;
    DuelSettled: TypedContractEvent<
      DuelSettledEvent.InputTuple,
      DuelSettledEvent.OutputTuple,
      DuelSettledEvent.OutputObject
    >;

    "FeeTransferred(uint256,address,uint256,uint256)": TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;
    FeeTransferred: TypedContractEvent<
      FeeTransferredEvent.InputTuple,
      FeeTransferredEvent.OutputTuple,
      FeeTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
