/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace HoneycombBondingCurveMarket {
  export type MarketStateStruct = {
    nativeReserve: BigNumberish;
    tokenReserve: BigNumberish;
    totalRaisedNative: BigNumberish;
    tradingStartTime: BigNumberish;
    graduated: boolean;
    initialized: boolean;
  };

  export type MarketStateStructOutput = [
    nativeReserve: bigint,
    tokenReserve: bigint,
    totalRaisedNative: bigint,
    tradingStartTime: bigint,
    graduated: boolean,
    initialized: boolean
  ] & {
    nativeReserve: bigint;
    tokenReserve: bigint;
    totalRaisedNative: bigint;
    tradingStartTime: bigint;
    graduated: boolean;
    initialized: boolean;
  };
}

export interface HoneycombBondingCurveMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "FEE_BPS"
      | "buy"
      | "cooldownSeconds"
      | "factory"
      | "feeVault"
      | "getBuyQuote"
      | "getMarketState"
      | "getPrice"
      | "getSellQuote"
      | "graduationThreshold"
      | "initialVirtualNative"
      | "initialVirtualToken"
      | "initializeMarket"
      | "lastTradeTime"
      | "launchDelay"
      | "markets"
      | "maxBuyPerTx"
      | "migrationContract"
      | "owner"
      | "renounceOwnership"
      | "sell"
      | "setCooldownSeconds"
      | "setFactory"
      | "setFeeVault"
      | "setGraduationThreshold"
      | "setLaunchDelay"
      | "setMaxBuyPerTx"
      | "setMigrationContract"
      | "transferOwnership"
      | "withdrawForMigration"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Graduated"
      | "MarketInitialized"
      | "OwnershipTransferred"
      | "Trade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBuyQuote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "graduationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialVirtualNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialVirtualToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastTradeTime",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "launchDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxBuyPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrationContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldownSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGraduationThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLaunchDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBuyPerTx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMigrationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawForMigration",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cooldownSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "graduationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialVirtualNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialVirtualToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTradeTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxBuyPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migrationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCooldownSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGraduationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLaunchDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxBuyPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMigrationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawForMigration",
    data: BytesLike
  ): Result;
}

export namespace GraduatedEvent {
  export type InputTuple = [token: AddressLike, totalRaised: BigNumberish];
  export type OutputTuple = [token: string, totalRaised: bigint];
  export interface OutputObject {
    token: string;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketInitializedEvent {
  export type InputTuple = [
    token: AddressLike,
    nativeReserve: BigNumberish,
    tokenReserve: BigNumberish,
    tradingStart: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    nativeReserve: bigint,
    tokenReserve: bigint,
    tradingStart: bigint
  ];
  export interface OutputObject {
    token: string;
    nativeReserve: bigint;
    tokenReserve: bigint;
    tradingStart: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    token: AddressLike,
    trader: AddressLike,
    isBuy: boolean,
    nativeAmt: BigNumberish,
    tokenAmt: BigNumberish,
    fee: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    trader: string,
    isBuy: boolean,
    nativeAmt: bigint,
    tokenAmt: bigint,
    fee: bigint,
    price: bigint
  ];
  export interface OutputObject {
    token: string;
    trader: string;
    isBuy: boolean;
    nativeAmt: bigint;
    tokenAmt: bigint;
    fee: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneycombBondingCurveMarket extends BaseContract {
  connect(runner?: ContractRunner | null): HoneycombBondingCurveMarket;
  waitForDeployment(): Promise<this>;

  interface: HoneycombBondingCurveMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [token: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;

  cooldownSeconds: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  feeVault: TypedContractMethod<[], [string], "view">;

  getBuyQuote: TypedContractMethod<
    [token: AddressLike, nativeIn: BigNumberish],
    [[bigint, bigint] & { tokensOut: bigint; fee: bigint }],
    "view"
  >;

  getMarketState: TypedContractMethod<
    [token: AddressLike],
    [HoneycombBondingCurveMarket.MarketStateStructOutput],
    "view"
  >;

  getPrice: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getSellQuote: TypedContractMethod<
    [token: AddressLike, tokenAmountIn: BigNumberish],
    [[bigint, bigint] & { nativeOut: bigint; fee: bigint }],
    "view"
  >;

  graduationThreshold: TypedContractMethod<[], [bigint], "view">;

  initialVirtualNative: TypedContractMethod<[], [bigint], "view">;

  initialVirtualToken: TypedContractMethod<[], [bigint], "view">;

  initializeMarket: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  lastTradeTime: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  launchDelay: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean] & {
        nativeReserve: bigint;
        tokenReserve: bigint;
        totalRaisedNative: bigint;
        tradingStartTime: bigint;
        graduated: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;

  maxBuyPerTx: TypedContractMethod<[], [bigint], "view">;

  migrationContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [
      token: AddressLike,
      tokenAmountIn: BigNumberish,
      minNativeOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setCooldownSeconds: TypedContractMethod<
    [_cooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeVault: TypedContractMethod<
    [_feeVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setGraduationThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLaunchDelay: TypedContractMethod<
    [_delay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxBuyPerTx: TypedContractMethod<
    [_maxBuy: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMigrationContract: TypedContractMethod<
    [_migration: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawForMigration: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { nativeAmount: bigint; tokenAmount: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [token: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cooldownSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBuyQuote"
  ): TypedContractMethod<
    [token: AddressLike, nativeIn: BigNumberish],
    [[bigint, bigint] & { tokensOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketState"
  ): TypedContractMethod<
    [token: AddressLike],
    [HoneycombBondingCurveMarket.MarketStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmountIn: BigNumberish],
    [[bigint, bigint] & { nativeOut: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "graduationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialVirtualNative"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialVirtualToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initializeMarket"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastTradeTime"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "launchDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean] & {
        nativeReserve: bigint;
        tokenReserve: bigint;
        totalRaisedNative: bigint;
        tradingStartTime: bigint;
        graduated: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxBuyPerTx"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "migrationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      token: AddressLike,
      tokenAmountIn: BigNumberish,
      minNativeOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCooldownSeconds"
  ): TypedContractMethod<[_cooldown: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeVault"
  ): TypedContractMethod<[_feeVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGraduationThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLaunchDelay"
  ): TypedContractMethod<[_delay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxBuyPerTx"
  ): TypedContractMethod<[_maxBuy: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMigrationContract"
  ): TypedContractMethod<[_migration: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawForMigration"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { nativeAmount: bigint; tokenAmount: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "Graduated"
  ): TypedContractEvent<
    GraduatedEvent.InputTuple,
    GraduatedEvent.OutputTuple,
    GraduatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketInitialized"
  ): TypedContractEvent<
    MarketInitializedEvent.InputTuple,
    MarketInitializedEvent.OutputTuple,
    MarketInitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;

  filters: {
    "Graduated(address,uint256)": TypedContractEvent<
      GraduatedEvent.InputTuple,
      GraduatedEvent.OutputTuple,
      GraduatedEvent.OutputObject
    >;
    Graduated: TypedContractEvent<
      GraduatedEvent.InputTuple,
      GraduatedEvent.OutputTuple,
      GraduatedEvent.OutputObject
    >;

    "MarketInitialized(address,uint256,uint256,uint256)": TypedContractEvent<
      MarketInitializedEvent.InputTuple,
      MarketInitializedEvent.OutputTuple,
      MarketInitializedEvent.OutputObject
    >;
    MarketInitialized: TypedContractEvent<
      MarketInitializedEvent.InputTuple,
      MarketInitializedEvent.OutputTuple,
      MarketInitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Trade(address,address,bool,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
  };
}
