/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace HoneycombPostBond {
  export type ChallengeStruct = {
    id: BigNumberish;
    postId: BigNumberish;
    challenger: AddressLike;
    stake: BigNumberish;
    reasonCID: string;
    openedAt: BigNumberish;
    resolvedAt: BigNumberish;
    outcome: BigNumberish;
  };

  export type ChallengeStructOutput = [
    id: bigint,
    postId: bigint,
    challenger: string,
    stake: bigint,
    reasonCID: string,
    openedAt: bigint,
    resolvedAt: bigint,
    outcome: bigint
  ] & {
    id: bigint;
    postId: bigint;
    challenger: string;
    stake: bigint;
    reasonCID: string;
    openedAt: bigint;
    resolvedAt: bigint;
    outcome: bigint;
  };

  export type PostStruct = {
    id: BigNumberish;
    agentId: BigNumberish;
    owner: AddressLike;
    contentCID: string;
    bondAmount: BigNumberish;
    createdAt: BigNumberish;
    challenged: boolean;
    resolved: boolean;
    removed: boolean;
  };

  export type PostStructOutput = [
    id: bigint,
    agentId: bigint,
    owner: string,
    contentCID: string,
    bondAmount: bigint,
    createdAt: bigint,
    challenged: boolean,
    resolved: boolean,
    removed: boolean
  ] & {
    id: bigint;
    agentId: bigint;
    owner: string;
    contentCID: string;
    bondAmount: bigint;
    createdAt: bigint;
    challenged: boolean;
    resolved: boolean;
    removed: boolean;
  };
}

export interface HoneycombPostBondInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CHALLENGER_SHARE"
      | "DEFAULT_ADMIN_ROLE"
      | "MODERATOR_ROLE"
      | "agentRegistry"
      | "bondAmount"
      | "challengePost"
      | "challengeStake"
      | "challenges"
      | "createPost"
      | "getChallenge"
      | "getPost"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "postExists"
      | "postToChallenge"
      | "posts"
      | "renounceRole"
      | "resolveChallenge"
      | "revokeRole"
      | "setAgentRegistry"
      | "setBondAmount"
      | "setChallengeStake"
      | "setTreasury"
      | "supportsInterface"
      | "totalPosts"
      | "treasury"
      | "withdrawLockPeriod"
      | "withdrawPostBond"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondWithdrawn"
      | "ChallengeResolved"
      | "PostChallenged"
      | "PostCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHALLENGER_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MODERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengePost",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challenges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postToChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveChallenge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChallengeStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPosts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawLockPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPostBond",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CHALLENGER_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MODERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bondAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "challengePost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postToChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChallengeStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPosts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPostBond",
    data: BytesLike
  ): Result;
}

export namespace BondWithdrawnEvent {
  export type InputTuple = [
    postId: BigNumberish,
    owner: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    owner: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    owner: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeResolvedEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    postId: BigNumberish,
    outcome: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    challengeId: bigint,
    postId: bigint,
    outcome: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    challengeId: bigint;
    postId: bigint;
    outcome: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostChallengedEvent {
  export type InputTuple = [
    challengeId: BigNumberish,
    postId: BigNumberish,
    challenger: AddressLike,
    reasonCID: string,
    stake: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    challengeId: bigint,
    postId: bigint,
    challenger: string,
    reasonCID: string,
    stake: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    challengeId: bigint;
    postId: bigint;
    challenger: string;
    reasonCID: string;
    stake: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    agentId: BigNumberish,
    owner: AddressLike,
    contentCID: string,
    bondAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    agentId: bigint,
    owner: string,
    contentCID: string,
    bondAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    agentId: bigint;
    owner: string;
    contentCID: string;
    bondAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneycombPostBond extends BaseContract {
  connect(runner?: ContractRunner | null): HoneycombPostBond;
  waitForDeployment(): Promise<this>;

  interface: HoneycombPostBondInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CHALLENGER_SHARE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MODERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  bondAmount: TypedContractMethod<[], [bigint], "view">;

  challengePost: TypedContractMethod<
    [postId: BigNumberish, reasonCID: string],
    [bigint],
    "payable"
  >;

  challengeStake: TypedContractMethod<[], [bigint], "view">;

  challenges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        postId: bigint;
        challenger: string;
        stake: bigint;
        reasonCID: string;
        openedAt: bigint;
        resolvedAt: bigint;
        outcome: bigint;
      }
    ],
    "view"
  >;

  createPost: TypedContractMethod<
    [agentId: BigNumberish, contentCID: string],
    [bigint],
    "payable"
  >;

  getChallenge: TypedContractMethod<
    [challengeId: BigNumberish],
    [HoneycombPostBond.ChallengeStructOutput],
    "view"
  >;

  getPost: TypedContractMethod<
    [postId: BigNumberish],
    [HoneycombPostBond.PostStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  postExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  postToChallenge: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        agentId: bigint;
        owner: string;
        contentCID: string;
        bondAmount: bigint;
        createdAt: bigint;
        challenged: boolean;
        resolved: boolean;
        removed: boolean;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveChallenge: TypedContractMethod<
    [challengeId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentRegistry: TypedContractMethod<
    [_agentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setBondAmount: TypedContractMethod<
    [_bondAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setChallengeStake: TypedContractMethod<
    [_challengeStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalPosts: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  withdrawLockPeriod: TypedContractMethod<[], [bigint], "view">;

  withdrawPostBond: TypedContractMethod<
    [postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CHALLENGER_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MODERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bondAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengePost"
  ): TypedContractMethod<
    [postId: BigNumberish, reasonCID: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "challengeStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        postId: bigint;
        challenger: string;
        stake: bigint;
        reasonCID: string;
        openedAt: bigint;
        resolvedAt: bigint;
        outcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [agentId: BigNumberish, contentCID: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getChallenge"
  ): TypedContractMethod<
    [challengeId: BigNumberish],
    [HoneycombPostBond.ChallengeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPost"
  ): TypedContractMethod<
    [postId: BigNumberish],
    [HoneycombPostBond.PostStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "postExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "postToChallenge"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        agentId: bigint;
        owner: string;
        contentCID: string;
        bondAmount: bigint;
        createdAt: bigint;
        challenged: boolean;
        resolved: boolean;
        removed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveChallenge"
  ): TypedContractMethod<
    [challengeId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[_agentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBondAmount"
  ): TypedContractMethod<[_bondAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChallengeStake"
  ): TypedContractMethod<[_challengeStake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalPosts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawLockPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawPostBond"
  ): TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BondWithdrawn"
  ): TypedContractEvent<
    BondWithdrawnEvent.InputTuple,
    BondWithdrawnEvent.OutputTuple,
    BondWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeResolved"
  ): TypedContractEvent<
    ChallengeResolvedEvent.InputTuple,
    ChallengeResolvedEvent.OutputTuple,
    ChallengeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PostChallenged"
  ): TypedContractEvent<
    PostChallengedEvent.InputTuple,
    PostChallengedEvent.OutputTuple,
    PostChallengedEvent.OutputObject
  >;
  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "BondWithdrawn(uint256,address,uint256,uint256)": TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;
    BondWithdrawn: TypedContractEvent<
      BondWithdrawnEvent.InputTuple,
      BondWithdrawnEvent.OutputTuple,
      BondWithdrawnEvent.OutputObject
    >;

    "ChallengeResolved(uint256,uint256,uint8,uint256)": TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;
    ChallengeResolved: TypedContractEvent<
      ChallengeResolvedEvent.InputTuple,
      ChallengeResolvedEvent.OutputTuple,
      ChallengeResolvedEvent.OutputObject
    >;

    "PostChallenged(uint256,uint256,address,string,uint256,uint256)": TypedContractEvent<
      PostChallengedEvent.InputTuple,
      PostChallengedEvent.OutputTuple,
      PostChallengedEvent.OutputObject
    >;
    PostChallenged: TypedContractEvent<
      PostChallengedEvent.InputTuple,
      PostChallengedEvent.OutputTuple,
      PostChallengedEvent.OutputObject
    >;

    "PostCreated(uint256,uint256,address,string,uint256,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
