/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IBondingCurveMarket {
  export type MarketStateStruct = {
    nativeReserve: BigNumberish;
    tokenReserve: BigNumberish;
    totalRaisedNative: BigNumberish;
    tradingStartTime: BigNumberish;
    graduated: boolean;
    initialized: boolean;
  };

  export type MarketStateStructOutput = [
    nativeReserve: bigint,
    tokenReserve: bigint,
    totalRaisedNative: bigint,
    tradingStartTime: bigint,
    graduated: boolean,
    initialized: boolean
  ] & {
    nativeReserve: bigint;
    tokenReserve: bigint;
    totalRaisedNative: bigint;
    tradingStartTime: bigint;
    graduated: boolean;
    initialized: boolean;
  };
}

export interface IBondingCurveMarketInterface extends Interface {
  getFunction(
    nameOrSignature: "getMarketState" | "markets" | "withdrawForMigration"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMarketState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawForMigration",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMarketState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawForMigration",
    data: BytesLike
  ): Result;
}

export interface IBondingCurveMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IBondingCurveMarket;
  waitForDeployment(): Promise<this>;

  interface: IBondingCurveMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMarketState: TypedContractMethod<
    [token: AddressLike],
    [IBondingCurveMarket.MarketStateStructOutput],
    "view"
  >;

  markets: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean] & {
        nativeReserve: bigint;
        tokenReserve: bigint;
        totalRaisedNative: bigint;
        tradingStartTime: bigint;
        graduated: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;

  withdrawForMigration: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { nativeAmount: bigint; tokenAmount: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMarketState"
  ): TypedContractMethod<
    [token: AddressLike],
    [IBondingCurveMarket.MarketStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean] & {
        nativeReserve: bigint;
        tokenReserve: bigint;
        totalRaisedNative: bigint;
        tradingStartTime: bigint;
        graduated: boolean;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawForMigration"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { nativeAmount: bigint; tokenAmount: bigint }],
    "nonpayable"
  >;

  filters: {};
}
